name: vpp-merge-maketest

on:
  workflow_call:
    inputs:
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: true
        type: string
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PREFIX:
        description: "Prefix of the log directory"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PREFIX:
        description: "Prefix of the log directory"
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  merge-maketest:
    # yamllint disable-line rule:line-length
    name: ${{ inputs.GERRIT_CHANGE_NUMBER }}/${{ inputs.GERRIT_PATCHSET_NUMBER}}__${{ inputs.GERRIT_BRANCH }}__${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=${{ matrix.os }}
      - fdio:workflow=${{ github.run_id }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404', 'ubuntu2204', 'debian12']
        executor_arch: ['x86_64', 'aarch64']
        build_type: ['rel']
        exclude:
          # Exclude debian12 on aarch64 for all builds
          - os: 'debian12'
            executor_arch: 'aarch64'

    env:
      FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
      GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
      GERRIT_CHANGE_ID: ${{ inputs.GERRIT_CHANGE_ID }}
      GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
      GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
      GERRIT_EVENT_TYPE: ${{ inputs.GERRIT_EVENT_TYPE }}
      GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
      GERRIT_PATCHSET_REVISION: ${{ inputs.GERRIT_PATCHSET_REVISION }}
      GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
      GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
      LOG_PREFIX: ${{ inputs.LOG_PREFIX }}
      LOG_NAME: ""
      LOG_DIR: ""
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      BUILD_TYPE: ${{ matrix.build_type }}
      MAKE_PARALLEL_JOBS: 16
      TEST_JOBS: 4
      TEST_RETRIES: 3
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04'  }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04' }}
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      TUI_LINE: "*******************************************************************"
      VPP_TEARDOWN_TIMEOUT: 30

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Prepare Log Directory
        run: |
          set -euxo pipefail
          LOG_NAME="${{ env.LOG_PREFIX }}/merge-maketest-${{ matrix.build_type }}-${{ matrix.os }}-${{ inputs.FDIO_NAMESPACE }}-${{ matrix.executor_arch }}"
          echo "LOG_NAME=$LOG_NAME" >> "$GITHUB_ENV"
          LOG_DIR="$WORKSPACE/logs/$LOG_NAME"
          echo "LOG_DIR=$LOG_DIR" >> "$GITHUB_ENV"
          mkdir -p "$LOG_DIR"

      - name: Show Environment
        run: |
          set -euo pipefail
          env | sort | tee "$LOG_DIR/environment.log"

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Checkout VPP Gerrit Change
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-checkout-gerrit-change@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP Packages
        run: |
          set -euxo pipefail
          {
            cd "$WORKSPACE"
            # pkg-verify runs install-deps, install-ext-deps, and builds vpp packages
            make UNATTENDED=yes pkg-verify
            # force rebuild of vpp-opt-deps
            apt-get remove -y vpp-opt-deps || true
            make UNATTENDED=yes install-opt-deps || true
          } | tee "$LOG_DIR/build-all-packages.log"

      - name: Push Packages to Packagecloud
        if: always()
        run: |
          set -euxo pipefail
          pkgcloud_cmd=""
          vpp_pkgs=""

          create_deb_push_cmds()
          {
              local distro="$(/usr/bin/facter operatingsystem)"
              local codename="$(/usr/bin/facter lsbdistcodename)"
              local downloads_dir="/root/Downloads"
              local pkgcloud_acct="fdio"

              echo '{"url":"https://packagecloud.io","token":"${{ secrets.PACKAGECLOUD_TOKEN }}"}' > /root/.packagecloud
              distro=${distro,,} # to lowercase
              codename=${codename,,} # to lowercase
              pkgcloud_cmd="package_cloud push ${pkgcloud_acct}/${GERRIT_BRANCH/stable\//}/${distro}/${codename}/main/ "
              if [ "$distro" = "debian" ] || [ "$distro" = "ubuntu" ] ; then
                  vpp_pkgs="$(find . -type f -iname '*.deb' | xargs || true)"
                  if [ -z "$vpp_pkgs" ] ; then
                      echo -e "\n$TUI_LINE\n* ERROR: No .deb packages found to push\n* PACKAGECLOUD PUSH FAILED!\n$TUI_LINE\n"
                      exit 1
                  fi
              else
                  echo -e "\n$TUI_LINE\n* ERROR: Unknown distro: '$distro'\n* PACKAGECLOUD PUSH FAILED!\n$TUI_LINE\n"
                  exit 1
              fi
          }

          if [ -f ~/.packagecloud ]; then
              cd "$WORKSPACE"
              create_deb_push_cmds
              for pkg in $vpp_pkgs ; do
                  $pkgcloud_cmd $pkg || true
              done
              # remove vpp-opt-deps before running make test
              apt-get remove -y vpp-opt-deps || true
          else
              echo -e "\n$TUI_LINE\n* ERROR: Missing '~/.packagecloud' for user '$(id)'\n* PACKAGECLOUD PUSH FAILED!\n$TUI_LINE\n"
              exit 1
          fi
          echo -e "\n$TUI_LINE\n* PACKAGECLOUD PUSH COMPLETE\n$TUI_LINE\n"

      - name: Post Packagecloud Push
        if: always()
        run: |
          echo '{"url":"https://packagecloud.io","token":"$token"}' > /root/.packagecloud

      - name: Setup Docker VPP Runtime Environment for 'make test'
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-docker-runtime-setup@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          SHM_SIZE: ${{ env.SHM_SIZE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: VPP Make Test
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-make-test@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        timeout-minutes: 120
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          TEST_JOBS: ${{ env.TEST_JOBS }}
          TEST_RETRIES: ${{ env.TEST_RETRIES }}
          MAKE_TEST_OS: ${{ env.MAKE_TEST_OS }}
          MAKE_TEST_MULTIWORKER_OS: ${{ env.MAKE_TEST_MULTIWORKER_OS }}
          VPPAPIGEN_TEST_OS: ${{ env.VPPAPIGEN_TEST_OS }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: AWS S3 Publish Logs
        if: always()
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/aws-s3-publish-logs@c2df5c7959a8415f7dd730315a40b058748b4c84
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}
          s3_path: ${{ env.LOG_NAME }}
          archives_path: ${{ env.LOG_DIR }}

      - name: Check Archives Directory
        id: check-archives
        if: always()
        run: |
          set -euxo pipefail
          archives_dir="$WORKSPACE/archives"
          if [[ -d "$archives_dir" ]] && find "$archives_dir" -type f -print -quit | grep -q . ; then
            echo "has_archives=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_archives=false" >> "$GITHUB_OUTPUT"
          fi

      - name: AWS S3 Publish Archives
        if: ${{ always() && steps.check-archives.outputs.has_archives == 'true' }}
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/aws-s3-publish-logs@c2df5c7959a8415f7dd730315a40b058748b4c84
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}
          s3_path: ${{ env.LOG_NAME }}
          archives_path: ${{ env.WORKSPACE }}/archives
