name: vpp-verify-gcc

on:
  workflow_call:
    inputs:
      CI_TIMESTAMP:
        description: "Start verify timestamp"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: true
        type: string
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PATH:
        description: "Sub-path to the log directory"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      CI_TIMESTAMP:
        description: "Start verify timestamp"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PATH:
        description: "Sub-path to the log directory"
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  verify-gcc:
    # yamllint disable-line rule:line-length
    name: ${{ inputs.GERRIT_CHANGE_NUMBER }}/${{ inputs.GERRIT_PATCHSET_NUMBER}}__${{ inputs.GERRIT_BRANCH }}__${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu2404']
        executor_arch: ['x86_64']
        build_type: ['dbg', 'rel']

    env:
      CI_TIMESTAMP: ${{ inputs.CI_TIMESTAMP }}
      FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
      GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
      GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
      GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
      GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
      GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
      GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
      LOG_PATH: ${{ inputs.LOG_PATH }}
      LOG_DIR: /scratch/docker-build/vpp/logs/${{ inputs.LOG_PATH }}/gcc-${{ matrix.build_type }}-${{ matrix.os }}-${{ inputs.FDIO_NAMESPACE }}-${{ matrix.executor_arch }}
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      MAKE_PARALLEL_JOBS: 16
      # MAKE_TEST_SUITES: "vlib vppinfra vpe_api vapi cli bihash"
      # NOTE: bihash tests are excluded due to known failures on GCOV builds,
      #       which due to a bug in the jenkins gcc job script is not properly
      #       detected and reported in the current CI job debug image test (e.g.
      #       the debug test does not build with GCOV enabled).  The gcov periodic job
      #       does fail bihash tests.
      MAKE_TEST_SUITES: "vlib vppinfra vpe_api vapi cli"
      TEST_JOBS: 16
      TEST_RETRIES: 3
      MAKE_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04'  }}
      MAKE_TEST_MULTIWORKER_OS: 'debian-12'
      VPPAPIGEN_TEST_OS: ${{ matrix.os == 'ubuntu2204' && 'ubuntu-22.04' || 'ubuntu-24.04' }}
      SHM_SIZE: ${{ matrix.executor_arch == 'aarch64' && '4096M' || '2048M' }}
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Prepare Log Directory
        run: |
          set -euxo pipefail
          mkdir -p "$LOG_DIR"

      - name: Show Environment
        run: |
          set -euo pipefail
          env | sort | tee "$LOG_DIR/environment.log"

      - name: Log GCC Build Start
        run: |
          set -euxo pipefail
          {
            echo "$TUI_LINE"
            echo "* $CI_TIMESTAMP: Starting GCC/GCOV build & tests"
            echo "$TUI_LINE"
          } | tee "$LOG_DIR/gcc_start.log"

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Checkout VPP Gerrit Change
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-checkout-gerrit-change@3cadd680be3814d9737a341c0b563f3441157a7c
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-install-deps@f9e0f384d665800c8e580da853e26558dd6d2668
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-install-ext-deps@f9e0f384d665800c8e580da853e26558dd6d2668
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP with GCC/GCOV
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-build@f9e0f384d665800c8e580da853e26558dd6d2668
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          MAKE_PARALLEL_JOBS: ${{ env.MAKE_PARALLEL_JOBS }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          USE_GCC: "true"
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Setup Docker VPP Runtime Environment for 'make test'
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-docker-runtime-setup@f9e0f384d665800c8e580da853e26558dd6d2668
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          SHM_SIZE: ${{ env.SHM_SIZE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: VPP Make Test with GCC/GCOV
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-make-test@f9e0f384d665800c8e580da853e26558dd6d2668
        timeout-minutes: 90
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          BUILD_TYPE: ${{ matrix['build_type'] }}
          MAKE_TEST_SUITES: ${{ env.MAKE_TEST_SUITES }}
          TEST_JOBS: ${{ env.TEST_JOBS }}
          TEST_RETRIES: ${{ env.TEST_RETRIES }}
          MAKE_TEST_OS: ${{ env.MAKE_TEST_OS }}
          MAKE_TEST_MULTIWORKER_OS: ${{ env.MAKE_TEST_MULTIWORKER_OS }}
          VPPAPIGEN_TEST_OS: ${{ env.VPPAPIGEN_TEST_OS }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Show GCC Logs
        if: always()
        run: |
          set -euo pipefail
          echo "Log directory: $LOG_DIR"
          ls -l "$LOG_DIR"
          for file in $(ls "$LOG_DIR"); do
            echo -e "\n\n-----[ $file ]-----\n"
            cat "$LOG_DIR/$file"
            echo "-----"
          done

      - name: Report Success
        if: success()
        run: |
          echo "::notice::VPP Verify GCC/GCOV workflow completed successfully!"
          echo "Workflow ID: ${{ github.run_id }}"
          echo "Name: ${{ github.workflow }}"
          echo "Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
          echo "Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
