name: vpp-verify-arm-drivers

on:
  workflow_call:
    inputs:
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: true
        type: string
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PREFIX:
        description: "Prefix of the log directory"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PREFIX:
        description: "Prefix of the log directory"
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  verify-arm-drivers:
    # yamllint disable-line rule:line-length
    name: ${{ inputs.GERRIT_CHANGE_NUMBER }}/${{ inputs.GERRIT_PATCHSET_NUMBER}}__${{ inputs.GERRIT_BRANCH }}__${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=${{ matrix.class }}
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=${{ matrix.os }}
      - fdio:workflow=${{ github.run_id }}

    strategy:
      fail-fast: false
      matrix:
        build_type: ['release']
        class: ['builder']
        os: ['ubuntu2404']
        executor_arch: ['aarch64']

    env:
      FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
      GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
      GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
      GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
      GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
      GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
      GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
      LOG_PREFIX: ${{ inputs.LOG_PREFIX }}
      LOG_NAME: ""
      LOG_DIR: ""
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v6

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Prepare Log Directory
        run: |
          set -euxo pipefail
          LOG_NAME="${{ env.LOG_PREFIX }}/verify-arm-drivers-${{ matrix.build_type }}-${{ matrix.class }}-${{ matrix.os }}-${{ inputs.FDIO_NAMESPACE }}-${{ matrix.executor_arch }}"
          echo "LOG_NAME=$LOG_NAME" >> "$GITHUB_ENV"
          LOG_DIR="$WORKSPACE/logs/$LOG_NAME"
          echo "LOG_DIR=$LOG_DIR" >> "$GITHUB_ENV"
          mkdir -p "$LOG_DIR"

      - name: Show Environment
        run: |
          set -euo pipefail
          ls -l "$LOG_DIR"
          env | sort | tee "$LOG_DIR/environment.log"

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Checkout VPP Gerrit Change
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-checkout-gerrit-change@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        uses: fdio/vpp/.github/actions/vpp-install-deps@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        uses: fdio/vpp/.github/actions/vpp-install-ext-deps@f1396ffb623d0a03f8942b7262a18a591ded6cf3
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP ARM Drivers
        run: |
          set -euxo pipefail
          cd "$WORKSPACE"
          ls -l "$LOG_DIR"
          BUILD_RESULT="* SUCCESSFULLY COMPLETED"
          BUILD_ERROR=""
          RETVAL="0"
          make_pkg_verify_arm_driver() {
              vpp_platform="$1"
              git clean -fdx build build-root src test || true
              if ! make UNATTENDED=yes pkg-verify VPP_PLATFORM="$vpp_platform" ; then
                  BUILD_ERROR+="* FAILED 'make UNATTENDED=yes pkg-verify VPP_PLATFORM=$vpp_platform'\n"
              fi
          }
          if [ -f $WORKSPACE/extras/scripts/build_static_vppctl.sh ] ; then
              if ! $WORKSPACE/extras/scripts/build_static_vppctl.sh ; then
                  BUILD_ERROR="* FAILED '$WORKSPACE/extras/scripts/build_static_vppctl.sh'\n"
              fi
          fi
          make_pkg_verify_arm_driver cn913x | tee "$LOG_DIR/arm_driver_build_cn913x.log"
          make_pkg_verify_arm_driver octeon9 | tee "$LOG_DIR/arm_driver_build_octeon9.log"
          make_pkg_verify_arm_driver octeon10 | tee "$LOG_DIR/arm_driver_build_octeon10.log"
          {
            if [ -n "$BUILD_ERROR" ] ; then
                BUILD_RESULT="$BUILD_ERROR"
                RETVAL="1"
            fi
            echo -e "\n$TUI_LINE\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^} ARM DRIVERS BUILD\n$BUILD_RESULT\n$TUI_LINE\n"
          } | tee "$LOG_DIR/arm_driver_build_results.log"
          exit "$RETVAL"

      - name: AWS S3 Publish Logs
        if: always()
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/aws-s3-publish-logs@c2df5c7959a8415f7dd730315a40b058748b4c84
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          s3_bucket: ${{ vars.S3_BUCKET }}
          s3_path: ${{ env.LOG_NAME }}
          archives_path: ${{ env.LOG_DIR }}
