name: vpp-verify-dpdk-rdma-ver

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2am UTC
  workflow_dispatch:
    inputs:
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod

env:
  FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

concurrency:
  group: required-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  verify-dpdk-rdma-version:
    # yamllint disable-line rule:line-length
    name: ${{ inputs.GERRIT_CHANGE_NUMBER }}/${{ inputs.GERRIT_PATCHSET_NUMBER}}__${{ inputs.GERRIT_BRANCH }}__${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=ubuntu2404

    env:
      WORKSPACE: /scratch/docker-build/vpp
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Show Environment
        run: |
          env | sort

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Pull VPP master HEAD
        run: |
          set -euxo pipefail
          cd $WORKSPACE
          git checkout master
          git pull
          git show --stat

      - name: Install VPP dependencies
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-install-ext-deps@f9e0f384d665800c8e580da853e26558dd6d2668
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: VPP Make Coverage Test
        timeout-minutes: 90
        run: |
          set -euo pipefail

          EXTERNAL_BUILD_DIR="$WORKSPACE/build/external"
          RETVAL="0"
          MISMATCH_RESULT="INCLUDED IN"

          make -C "$EXTERNAL_BUILD_DIR" build-deb
          source "$EXTERNAL_BUILD_DIR/dpdk_mlx_default.sh" || true

          if [ "${DPDK_MLX_DEFAULT-}" = "n" ] ; then
              MISMATCH_RESULT="MISSING FROM"
              RETVAL="1"
          fi
          echo -e "\n$TUI_LINE\n* MLX DPDK DRIVER $MISMATCH_RESULT VPP-EXT-DEPS PACKAGE\n$TUI_LINE\n"
          exit $RETVAL

      - name: Report Success
        if: success()
        run: |
          echo "::notice::VPP DPDK RDMA Version workflow completed successfully!"
          echo "Workflow ID: ${{ github.run_id }}"
          echo "Name: ${{ github.workflow }}"
