name: vpp-verify-arm-drivers

on:
  workflow_call:
    inputs:
      CI_TIMESTAMP:
        description: "Start verify timestamp"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: true
        type: string
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PATH:
        description: "Sub-path to the log directory"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      CI_TIMESTAMP:
        description: "Start verify timestamp"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      LOG_PATH:
        description: "Sub-path to the log directory"
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  verify-arm-drivers:
    # yamllint disable-line rule:line-length
    name: ${{ inputs.GERRIT_CHANGE_NUMBER }}/${{ inputs.GERRIT_PATCHSET_NUMBER}}__${{ inputs.GERRIT_BRANCH }}__${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=${{ matrix.class }}
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build_type: ['release']
        class: ['builder']
        os: ['ubuntu2404']
        executor_arch: ['aarch64']

    env:
      CI_TIMESTAMP: ${{ inputs.CI_TIMESTAMP }}
      FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
      GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
      GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
      GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
      GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
      GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
      GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
      LOG_PATH: ${{ inputs.LOG_PATH }}
      LOG_DIR: /scratch/docker-build/vpp/logs/${{ inputs.LOG_PATH }}/arm-drivers-${{ matrix.build_type }}-${{ matrix.class }}-${{ matrix.os }}-${{ inputs.FDIO_NAMESPACE }}-${{ matrix.executor_arch }}
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/${{ matrix.os }}-${{ matrix.executor_arch }}
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Prepare Log Directory
        run: |
          set -euxo pipefail
          mkdir -p "$LOG_DIR"

      - name: Show Environment
        run: |
          set -euo pipefail
          ls -l "$LOG_DIR"
          env | sort | tee "${{ env.LOG_DIR }}/environment.log"

      - name: Log ARM Driver Build Start
        run: |
          set -euxo pipefail
          ls -l "$LOG_DIR"
          {
            echo "$TUI_LINE"
            echo "* $CI_TIMESTAMP: Starting ARM driver build"
            echo "$TUI_LINE"
          } | tee "$LOG_DIR/arm_driver_start.log"

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Checkout VPP Gerrit Change
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-checkout-gerrit-change@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        uses: fdio/vpp/.github/actions/vpp-install-deps@master
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        uses: fdio/vpp/.github/actions/vpp-install-ext-deps@master
        with:
          LOG_DIR: ${{ env.LOG_DIR }}
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP ARM Drivers
        run: |
          set -euxo pipefail
          cd "$WORKSPACE"
          ls -l "$LOG_DIR"
          BUILD_RESULT="* SUCCESSFULLY COMPLETED"
          BUILD_ERROR=""
          RETVAL="0"
          make_pkg_verify_arm_driver() {
              vpp_platform="$1"
              git clean -fdx || true
              if ! make UNATTENDED=yes pkg-verify VPP_PLATFORM="$vpp_platform"; then
                  BUILD_ERROR+="* FAILED 'make UNATTENDED=yes pkg-verify VPP_PLATFORM=$vpp_platform'\n"
              fi
          }
          if [ -f $WORKSPACE/extras/scripts/build_static_vppctl.sh ] ; then
              if ! $WORKSPACE/extras/scripts/build_static_vppctl.sh ; then
                  BUILD_ERROR="FAILED '$WORKSPACE/extras/scripts/build_static_vppctl.sh'"
                  return
              fi
          fi
          make_pkg_verify_arm_driver cn913x | tee "$LOG_DIR/arm_driver_build_cn913x.log"
          make_pkg_verify_arm_driver octeon9 | tee "$LOG_DIR/arm_driver_build_octeon9.log"
          make_pkg_verify_arm_driver octeon10 | tee "$LOG_DIR/arm_driver_build_octeon10.log"
          {
            if [ -n "$BUILD_ERROR" ] ; then
                BUILD_RESULT="$BUILD_ERROR"
                RETVAL="1"
            fi
            echo -e "\n$TUI_LINE\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^} ARM DRIVERS BUILD\n$BUILD_RESULT\n$TUI_LINE\n"
          } | tee "$LOG_DIR/arm_driver_build_results.log"
          exit "$RETVAL"

      - name: Show ARM Driver Logs
        if: always()
        run: |
          set -euo pipefail
          if [ -d "$LOG_DIR" ] ; then
            echo "Log directory: $LOG_DIR"
            echo "cat $LOG_DIR/arm_driver_start.log"
            cat "$LOG_DIR/arm_driver_start.log"
            ls -l "$LOG_DIR"
            for file in $(ls "$LOG_DIR") ; do
              echo -e "\n-----[ $file ]-----\n"
              cat "$LOG_DIR/$file"
              echo "-----"
            done
          else
            echo "ERROR: log dir does not exist!"
          fi

      - name: Report Success
        if: success()
        run: |
          echo "::notice::VPP Verify ARM Drivers workflow completed successfully!"
          echo "Workflow ID: ${{ github.run_id }}"
          echo "Name: ${{ github.workflow }}"
          echo "Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
          echo "Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
