name: vpp-verify-arm-drivers

on:
  workflow_call:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: string
        default: prod
  workflow_dispatch:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      FDIO_NAMESPACE:
        description: "Executor Namespace (prod|sandbox)"
        required: false
        type: choice
        options:
          - sandbox
          - prod
        default: prod

defaults:
  run:
    shell: bash

permissions:
  contents: read
  actions: read

jobs:
  verify-arm-drivers:
    name: verify-arm-drivers-${{ inputs.GERRIT_BRANCH }}-${{ inputs.FDIO_NAMESPACE }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=aarch64
      - fdio:class=builder
      - fdio:namespace=${{ inputs.FDIO_NAMESPACE || 'prod' }}
      - fdio:os=ubuntu2404

    env:
      WORKSPACE: /scratch/docker-build/vpp
      CCACHE_DIR: /scratch/ccache/ubuntu2404-aarch64
      MAKE_PARALLEL_JOBS: 16
      GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
      GERRIT_CHANGE_URL: ${{ inputs.GERRIT_CHANGE_URL }}
      GERRIT_PROJECT: ${{ inputs.GERRIT_PROJECT }}
      GERRIT_REFSPEC: ${{ inputs.GERRIT_REFSPEC }}
      GERRIT_CHANGE_NUMBER: ${{ inputs.GERRIT_CHANGE_NUMBER }}
      GERRIT_PATCHSET_NUMBER: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
      FDIO_NAMESPACE: ${{ inputs.FDIO_NAMESPACE }}
      TUI_LINE: "*******************************************************************"

    steps:
      - name: Actions Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/setup-executor-env@b728d1589228e2891a4241a1bba362d76895c225

      - name: Show Environment
        run: |
          env | sort

      - name: Show Nomad Dockerfile
        # yamllint disable-line rule:line-length
        uses: fdio/.github/.github/actions/show-nomad-dockerfile@b728d1589228e2891a4241a1bba362d76895c225

      - name: Checkout VPP Gerrit Change
        # yamllint disable-line rule:line-length
        uses: fdio/vpp/.github/actions/vpp-checkout-gerrit-change@3cadd680be3814d9737a341c0b563f3441157a7c
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          GERRIT_BRANCH: ${{ env.GERRIT_BRANCH }}
          GERRIT_REFSPEC: ${{ env.GERRIT_REFSPEC }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP dependencies
        uses: fdio/vpp/.github/actions/vpp-install-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Install VPP external dependencies
        uses: fdio/vpp/.github/actions/vpp-install-ext-deps@master
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          TUI_LINE: ${{ env.TUI_LINE }}

      - name: Build VPP ARM Drivers
        run: |
          set -euxo pipefail
          cd $WORKSPACE
          BUILD_RESULT="* SUCCESSFULLY COMPLETED"
          BUILD_ERROR=""
          RETVAL="0"

          make_pkg_verify_arm_driver() {
              vpp_platform="$1"
              git clean -fdx || true
              if ! make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} pkg-verify VPP_PLATFORM="$vpp_platform"; then
                  BUILD_ERROR+="* FAILED 'make UNATTENDED=yes MAKE_PARALLEL_JOBS=${MAKE_PARALLEL_JOBS} pkg-verify VPP_PLATFORM=$vpp_platform'\n"
              fi
          }

          make_pkg_verify_arm_driver cn913x
          make_pkg_verify_arm_driver octeon9
          make_pkg_verify_arm_driver octeon10

          if [ -n "$BUILD_ERROR" ] ; then
              BUILD_RESULT="$BUILD_ERROR"
              RETVAL="1"
          fi
          echo -e "\n$TUI_LINE\n* VPP ${OS_ID^^}-${OS_VERSION_ID}-${OS_ARCH^^} ARM DRIVERS BUILD\n$BUILD_RESULT\n$TUI_LINE\n"
          exit "$RETVAL"

      - name: Report Success
        if: success()
        run: |
          echo "::notice::VPP Verify ARM Drivers workflow completed successfully!"
          echo "Workflow ID: ${{ github.run_id }}"
          echo "Name: ${{ github.workflow }}"
          echo "Branch: $GERRIT_BRANCH, Change: $GERRIT_CHANGE_NUMBER, Patchset: $GERRIT_PATCHSET_NUMBER"
          echo "Gerrit Refspec: $GERRIT_REFSPEC, Gerrit Change URL: $GERRIT_CHANGE_URL"
